import React, { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  ar: {
    appName: 'نظام جمع البيانات',
    appSubtitle: 'منصة البحث والتدقيق',
    dashboard: 'لوحة التحكم',
    records: 'السجلات',
    import: 'استيراد البيانات',
    export: 'تصدير البيانات',
    backup: 'النسخ الاحتياطي والاستعادة',
    settings: 'الإعدادات',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    userRole: 'مسؤول النظام',
    userName: 'أحمد',
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    language: 'اللغة',
    arabic: 'العربية',
    english: 'English',
    welcomeTitle: 'مرحباً بك في نظام إدارة وجمع البيانات',
    welcomeDesc: 'هذه الواجهة الرئيسية الهيكلية للنظام. يمكنك التنقل بين الأقسام من خلال القائمة الجانبية.',
    recordsPlaceholderTitle: 'قسم إدارة السجلات',
    recordsPlaceholderDesc: 'هذه الصفحة مخصصة لعرض واستعلام وإدارة بيانات أرقام الهواتف والسجلات (صفحة هيكلية).',
    importPlaceholderTitle: 'قسم استيراد البيانات',
    importPlaceholderDesc: 'هذه الصفحة مخصصة لاستيراد ملفات CSV / XLSX / TXT وإضافتها للنظام (صفحة هيكلية).',
    exportPlaceholderTitle: 'قسم تصدير البيانات',
    exportPlaceholderDesc: 'هذه الصفحة مخصصة لتصدير واستخراج البيانات المفلترة إلى صيغ متعددة (صفحة هيكلية).',
    backupPlaceholderTitle: 'قسم النسخ الاحتياطي والاستعادة',
    backupPlaceholderDesc: 'هذه الصفحة مخصصة لإدارة النسخ الاحتياطية واستعادة قاعدة البيانات (صفحة هيكلية).',
    settingsPlaceholderTitle: 'قسم إعدادات النظام',
    settingsPlaceholderDesc: 'هذه الصفحة مخصصة لضبط خيارات وتفضيلات النظام والقواعد العامة (صفحة هيكلية).',
    loginPlaceholderTitle: 'تسجيل الدخول إلى النظام',
    loginPlaceholderDesc: 'أدخل بيانات الدخول للمتابعة إلى لوحة التحكم',
    usernameLabel: 'اسم المستخدم',
    usernamePlaceholder: 'أدخل اسم المستخدم...',
    passwordLabel: 'كلمة المرور',
    passwordPlaceholder: 'أدخل كلمة المرور...',
    loginBtn: 'تسجيل الدخول',
    invalidCredentials: 'اسم المستخدم أو كلمة المرور غير صحيحة!',
    defaultCredentialsHint: 'بيانات الدخول الافتراضية للعميل:',
    quickFill: 'ملء تلقائي (admin)',
    changePassword: 'تعديل بيانات الدخول',
    newUsername: 'اسم المستخدم الجديد',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور',
    credentialsUpdated: 'تم تحديث بيانات الدخول بنجاح!',
    passwordsDoNotMatch: 'كلمات المرور غير متطابقة!',
    systemStatus: 'حالة النظام الهيكلي',
    statusOk: 'جاهز وفعال',
    quickStats: 'نظرة عامة',
    totalRecords: 'إجمالي السجلات',
    systemVersion: 'إصدار النواة',
    demoMode: 'نموذج هيكلي متكامل',
    backToDashboard: 'العودة للوحة التحكم',
    cancel: 'إلغاء',
    save: 'حفظ',
    nameRequired: 'اسم العميل مطلوب!',
    recordSaved: 'تم حفظ السجل بنجاح!',
    modalSubtitle: 'أدخل بيانات السجل الجديد ثم اضغط حفظ',
    governorateLabel: 'المحافظة',
    governoratePlaceholder: 'اختر المحافظة...',
    actions: 'الإجراءات',
    edit: 'تعديل',
    delete: 'حذف',
    status: 'الحالة',
    statusActive: 'نشط',
    statusPending: 'قيد المراجعة',
    noRecordsFound: 'لم يتم العثور على أي سجلات تطابق بحثك',
    noRecordsYet: 'لا توجد سجلات حالياً في النظام. يمكنك إضافة سجل يدوياً بالضغط على "إضافة صف" أو استيراد ملف Excel.',
    editRecord: 'تعديل بيانات السجل',
    dataSource: 'مصدر البيانات',
    dataSourcePlaceholder: 'مثال: ملف إكسيل، فيسبوك، إدخال يدوي...',
    city: 'المدينة',
    cityPlaceholder: 'مثال: الرياض، جدة، الدمام، مكة...',
    activityType: 'نوع النشاط',
    activityTypePlaceholder: 'مثال: عقارات، مقاولات، مطاعم، تجارة...',
    confirmDelete: 'هل أنت متأكد من حذف هذا السجل؟',
    recordsTable: 'جدول السجلات',
    sortHint: 'اضغط على أي عمود للترتيب تصاعدياً أو تنازلياً ⇅',
    customBadge: 'إضافة على ذوق العميل',
    addedColumnsLabel: 'الأعمدة الإضافية المضافة للجدول:',
    loadingData: 'جاري تحميل البيانات...',
    showingRows: 'عرض',
    to: 'إلى',
    of: 'من إجمالي',
    recordsCount: 'سجل',
    perPage: 'لكل صفحة:',
    prevPage: 'الصفحة السابقة',
    nextPage: 'الصفحة التالية',
    clickToSort: 'اضغط للترتيب',

    // Records Page Translations
    recordsSubtitle: 'نظام جمع وبحث السجلات وأرقام الجوال والأنشطة التجارية في المملكة العربية السعودية',
    exportExcel: 'تصدير Excel',
    addRecord: 'إضافة صف (سجل جديد)',
    searchPlaceholder: 'ابحث برقم الجوال، الاسم، المدينة، مصدر البيانات، أو نوع النشاط...',
    filterBtn: 'تصفية وفلاتر',
    searchingFor: 'جاري البحث الحي عن:',
    clearSearchHint: '(اضغط علامة × للمسح السريع)',
    customColumnsTitle: 'ميزة إضافة حقول وأعمدة مخصصة على ذوق العميل:',
    customColumnsDesc: 'جرب تكتب اسم أي حقل جديد تحبه (مثلاً: "الرقم القومي", "الوظيفة", "ملاحظات") واضغط إضافة:',
    newColumnPlaceholder: 'اكتب اسم العمود الجديد...',
    addColumnBtn: 'إضافة عمود',
    currentColumns: 'الأعمدة الحالية في الجدول:',
    deleteColumnTitle: 'حذف هذا العمود',
    columnExistsError: 'هذا الحقل موجود بالفعل!',
    inputStatesTitle: 'أنواع وحالات حقول الإدخال (Input States):',
    phoneNumber: 'رقم الجوال',
    phonePlaceholder: '+966546064257',
    phoneHelper: 'رقم الجوال السعودي (مثال: +966546064257 أو 0546064257)',
    clientName: 'اسم العميل',
    clientPlaceholder: 'فهد عبد العزيز الشمري...',
    errorInputLabel: 'حقل به خطأ في الإدخال',
    errorInputVal: 'رقم غير صحيح',
    errorInputMsg: 'تنسيق رقم الجوال غير صالح! يجب أن يكون رقماً سعودياً (مثال: +966546064257 أو 0546064257)',
    disabledInputLabel: 'حقل معطل (Disabled)',
    disabledInputVal: 'قيمة غير قابلة للتعديل',
    defaultColPhone: 'رقم الجوال',
    defaultColName: 'الاسم',
    defaultColGov: 'المنطقة / المدينة',
  },
  en: {
    appName: 'Data Collection System',
    appSubtitle: 'Search & Verification Platform',
    dashboard: 'Dashboard',
    records: 'Records',
    import: 'Import Data',
    export: 'Export Data',
    backup: 'Backup & Restore',
    settings: 'Settings',
    login: 'Login',
    logout: 'Logout',
    userRole: 'System Administrator',
    userName: 'Ahmed',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    language: 'Language',
    arabic: 'العربية',
    english: 'English',
    welcomeTitle: 'Welcome to Data Management & Collection System',
    welcomeDesc: 'This is the application shell and structural foundation. You can navigate through sections using the sidebar.',
    recordsPlaceholderTitle: 'Records Management Section',
    recordsPlaceholderDesc: 'This page is designated for viewing, querying, and managing phone records (Structural Placeholder).',
    importPlaceholderTitle: 'Data Import Section',
    importPlaceholderDesc: 'This page is designated for importing CSV / XLSX / TXT files into the system (Structural Placeholder).',
    exportPlaceholderTitle: 'Data Export Section',
    exportPlaceholderDesc: 'This page is designated for exporting filtered data to multiple formats (Structural Placeholder).',
    backupPlaceholderTitle: 'Backup & Restore Section',
    backupPlaceholderDesc: 'This page is designated for managing backups and restoring the database (Structural Placeholder).',
    settingsPlaceholderTitle: 'System Settings Section',
    settingsPlaceholderDesc: 'This page is designated for configuring system settings and preferences (Structural Placeholder).',
    loginPlaceholderTitle: 'System Login',
    loginPlaceholderDesc: 'Enter your credentials to access the management dashboard',
    usernameLabel: 'Username',
    usernamePlaceholder: 'Enter your username...',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password...',
    loginBtn: 'Sign In',
    invalidCredentials: 'Invalid username or password!',
    defaultCredentialsHint: 'Default Client Credentials:',
    quickFill: 'Quick Fill (admin)',
    changePassword: 'Edit Login Credentials',
    newUsername: 'New Username',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    credentialsUpdated: 'Credentials updated successfully!',
    passwordsDoNotMatch: 'Passwords do not match!',
    systemStatus: 'Structural System Status',
    statusOk: 'Ready & Functional',
    quickStats: 'Quick Overview',
    totalRecords: 'Total Records',
    systemVersion: 'Core Version',
    demoMode: 'Structural Shell Active',
    backToDashboard: 'Back to Dashboard',
    cancel: 'Cancel',
    save: 'Save',
    nameRequired: 'Client name is required!',
    recordSaved: 'Record saved successfully!',
    modalSubtitle: 'Enter the new record details then click Save',
    governorateLabel: 'Governorate',
    governoratePlaceholder: 'Select governorate...',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    status: 'Status',
    statusActive: 'Active',
    statusPending: 'Pending',
    noRecordsFound: 'No records match your search criteria',
    noRecordsYet: 'No records in the system yet. You can add a record manually by clicking "Add Row" or import an Excel file.',
    editRecord: 'Edit Record',
    dataSource: 'Data Source',
    dataSourcePlaceholder: 'e.g. Excel File, Facebook, Manual...',
    city: 'City',
    cityPlaceholder: 'e.g. Riyadh, Jeddah, Dammam, Makkah...',
    activityType: 'Business Activity',
    activityTypePlaceholder: 'e.g. Real Estate, Contracting, Restaurant...',
    confirmDelete: 'Are you sure you want to delete this record?',
    recordsTable: 'Records Table',
    sortHint: 'Click on any column header to sort ⇅',
    customBadge: 'Client Custom Fields',
    addedColumnsLabel: 'Active Custom Columns:',
    loadingData: 'Loading data...',
    showingRows: 'Showing',
    to: 'to',
    of: 'of',
    recordsCount: 'records',
    perPage: 'Per page:',
    prevPage: 'Previous Page',
    nextPage: 'Next Page',
    clickToSort: 'Click to sort',

    // Records Page Translations
    recordsSubtitle: 'Saudi phone records, contacts, and business activities management system',
    exportExcel: 'Export Excel',
    addRecord: 'Add Row (New Record)',
    searchPlaceholder: 'Search by mobile number, name, city, data source, or activity...',
    filterBtn: 'Filters',
    searchingFor: 'Live searching for:',
    clearSearchHint: '(Click × to clear quickly)',
    customColumnsTitle: 'Dynamic Custom Fields & Columns (Client Preference):',
    customColumnsDesc: 'Type any new field name (e.g., "National ID", "Job Title", "Notes") and click add:',
    newColumnPlaceholder: 'Type new column name...',
    addColumnBtn: 'Add Column',
    currentColumns: 'Current Table Columns:',
    deleteColumnTitle: 'Delete this column',
    columnExistsError: 'This column already exists!',
    inputStatesTitle: 'Input Field States & Types:',
    phoneNumber: 'Mobile Number',
    phonePlaceholder: '+966546064257',
    phoneHelper: 'Saudi mobile number (e.g. +966546064257 or 0546064257)',
    clientName: 'Client Name',
    clientPlaceholder: 'Fahad Al-Shammari...',
    errorInputLabel: 'Field with Input Error',
    errorInputVal: 'Invalid Number',
    errorInputMsg: 'Invalid mobile number! Must be a valid Saudi number (e.g. +966546064257 or 0546064257)',
    disabledInputLabel: 'Disabled Field',
    disabledInputVal: 'Read-only value',
    defaultColPhone: 'Mobile Number',
    defaultColName: 'Name',
    defaultColGov: 'Region / City',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLang = localStorage.getItem('app-lang');
    return savedLang === 'en' || savedLang === 'ar' ? savedLang : 'ar';
  });

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.setAttribute('dir', dir);
    document.documentElement.setAttribute('lang', language);
    localStorage.setItem('app-lang', language);
  }, [language, dir]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'ar' ? 'en' : 'ar'));
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
